#!/usr/bin/env bash
set -e

echo "# Issue"
echo "## closed"
echo
PAGER=cat gh issue list --assignee @me --search "is:closed closed:>=$(date +%Y-%m-%d)" --json 'title,url' --jq '.[]|"  - [" + .title + "](" + .url + ")"' $@
echo
echo "## WIP"
echo
PAGER=cat gh issue list --assignee @me --search "updated:>=$(date +%Y-%m-%d)" --json 'title,url' --jq '.[]|"  - [" + .title + "](" + .url + ")"' $@
echo
echo "# PR"
echo "## WIP"
echo
PAGER=cat gh pr list --assignee @me --search "updated:>=$(date +%Y-%m-%d)" --json 'title,url' --jq '.[]|"  - [" + .title + "](" + .url + ")"' $@
echo
echo "## merged"
echo
PAGER=cat gh pr list --assignee @me --search "is:merged closed:>=$(date +%Y-%m-%d)" --json 'title,url' --jq '.[]|"  - [" + .title + "](" + .url + ")"' $@
echo
echo "## review-requested"
echo
PAGER=cat gh pr list --search "review-requested:@me" --json 'title,url' --jq '.[]|"  - [" + .title + "](" + .url + ")"' $@
echo
